### PR TITLE
[Code]Support bypass-TiDB write partition table with DataSource API

### LINKED ISSUE #2458: [BUG] Delete from condition on type BINARY or VARBINARY throw Exception
**Describe the bug**

Delete from condition on type BINARY or VARBINARY will throw Exception

**What did you do**
1. Use SQL client to create table:
```
create table `$database`.`$table` (id bigint, name varbinary(16) unique key) 
```
2. Use spark.sql to delete
```
spark.sql(
      s"delete from `tidb_catalog`.`$database`.`$table` where name = 'Mike'")
```

**What do you expect**

spark.sql() succeed.

**What happens instead**
image

**Additional context**
The reason is [code here](https://github.com/pingcap/tispark/blob/master/core/src/main/scala/com/pingcap/tispark/v2/TiDBTable.scala#L172-L176) doesn't work well with byte[].

### PR DESCRIPTION
**Pull request by xuanyu66**
### What problem does this PR solve? 
https://github.com/pingcap/tispark/pull/2438

### What is changed and how it works?
- locate partition and return the physical table.
- change methods in `WriteUtils` to two forms, one is supported for rdd, another is supported for row type.
```
  def generateRecordKVRDDToDelete(rdd: RDD[WrappedRow], tableId: Long): RDD[WrappedEncodedRow] 
  def generateRecordKVToDelete(wrappedRow: WrappedRow, tableId: Long): WrappedEncodedRow 
```
- add SparkContext in TiDelete in order to make RDD
- make method in `TiBatchWriteTable` use `TableCommon` instead of `TiTableInfo` as a physical table.
- use new DateTime() to avoid ConverException.
- close #2458 

### Check List 

Tests 

 - Unit test
 - Integration test

Side effects

 - Increased code complexity

Related changes

 - Need to update the documentation
 - Need to be included in the release note

### CODE REVIEW

File: core/src/main/scala/com/pingcap/tispark/write/TiBatchWriteTable.scala [hunk 1]
```diff
@@ -41,47 +42,35 @@ class TiBatchWriteTable(
...
-  private var isCommonHandle: Boolean = _
+  private val isCommonHandle = tiTable.getTableInfo.isCommonHandle
   private var deltaCount: Long = 0
   private var modifyCount: Long = 0
   @transient private var persistedDFList: List[DataFrame] = Nil
   @transient private var persistedRDDList: List[RDD[_]] = Nil
 
-  tiTableRef = options.getTiTableRef(tiConf)
-  tiDBInfo = tiSession.getCatalog.getDatabase(tiTableRef.databaseName)
-  tiTableInfo = tiSession.getCatalog.getTable(tiTableRef.databaseName, tiTableRef.tableName)
```
Comment (shiyuhang0) [inline core/src/main/scala/com/pingcap/tispark/write/TiBatchWriteTable.scala:72]: why not change it to `tiTableInfo=table.getTableInfo`. so you need not change when you use  tiTableInfo

File: core/src/main/scala/com/pingcap/tispark/write/TiDBDelete.scala [hunk 2]
```diff
@@ -40,53 +43,97 @@ case class TiDBDelete(
...
+            }
+          } else {
+            rowIterator.map { row =>
+              //Convert Spark row to TiKV row
+              val tiRow = WriteUtil.sparkRow2TiKVRow(row, tiTableInfo, colsInDf)
+              table -> tiRow
+            }
+          }
+        }
+        .collect())
```
[the remark this answers is not in the document]
Comment (xuanyu66) [reply core/src/main/scala/com/pingcap/tispark/write/TiDBDelete.scala:94]: add code comment to explain

File: core/src/main/scala/com/pingcap/tispark/write/TiDBDelete.scala [hunk 3]
```diff
@@ -40,53 +43,97 @@ case class TiDBDelete(
...
 
     //Extract handle
-    val deletion: RDD[WrappedRow] = tiRowRdd.map { row =>
-      WrappedRow(row, WriteUtil.extractHandle(row, tiTableInfo))
+    val deletionMapRDD: RDD[(TableCommon, WrappedRow)] = tiRowMapRDD.mapPartitions {
+      pairIterator =>
+        pairIterator.map {
+          case (table, tiRow) =>
+            table -> WrappedRow(tiRow, WriteUtil.extractHandle(tiRow, tiTableInfo))
+        }
```
[the remark this answers is not in the document]
Comment (xuanyu66) [reply core/src/main/scala/com/pingcap/tispark/write/TiDBDelete.scala:106]: There is some loss of legibility to use .1 .2

File: core/src/main/scala/com/pingcap/tispark/write/TiBatchWrite.scala [hunk 4]
```diff
@@ -146,15 +149,45 @@ class TiBatchWrite(
...
+            List(
+              new TiBatchWriteTable(
+                df,
+                tiContext,
+                physicalTableOptions,
+                tiConf,
+                tiDBJDBCClient,
+                isTiDBV4,
+                table))
+          }
```
[the remark this answers is not in the document]
Comment (xuanyu66) [reply core/src/main/scala/com/pingcap/tispark/write/TiBatchWrite.scala:190]: done

File: core/src/main/scala/com/pingcap/tispark/utils/WriteUtil.scala [hunk 5]
```diff
@@ -114,116 +118,152 @@ object WriteUtil {
...
       }
     }.toMap
   }
 
+  def generateIndexKVs(
+      rdd: WrappedRow,
+      tiTable: TableCommon,
+      remove: Boolean): mutable.Map[Long, mutable.Set[WrappedEncodedRow]] = {
+    val tableInfo = tiTable.getTableInfo
+    listPair2multimap(tableInfo.getIndices.asScala.flatMap { index =>
```
Comment (Daemonxiao) [inline core/src/main/scala/com/pingcap/tispark/utils/WriteUtil.scala:177]: How about `listPair2MutilMap`？

File: core/src/main/scala/com/pingcap/tispark/utils/WriteUtil.scala [hunk 6]
```diff
@@ -114,116 +118,152 @@ object WriteUtil {
...
+        None
+      } else {
+        Some((index.getId, generateIndex(rdd, index, tiTable, remove)))
+      }
+    }.toList)
+  }
+
   /**
    * mix the results that are produced by method generateIndexKVs
+   *
```
Comment (Daemonxiao) [inline core/src/main/scala/com/pingcap/tispark/utils/WriteUtil.scala:188]: Should @param `tiTableInfo` be `TableCommon`?

File: core/src/main/scala/com/pingcap/tispark/write/TiBatchWrite.scala [hunk 7]
```diff
@@ -146,15 +149,39 @@ class TiBatchWrite(
...
-            isTiDBV4)
+          val tableOptions = options.setDBTable(dbTable)
+          val tiTableRef = tableOptions.getTiTableRef(tiConf)
+          val tiTableInfo = tiContext.tiSession.getCatalog.getTable(
+            tableOptions.getTiTableRef(tiConf).databaseName,
+            tableOptions.getTiTableRef(tiConf).tableName)
+
+          if (tiTableInfo == null) {
+            throw new NoSuchTableException(tiTableRef.databaseName, tiTableRef.tableName)
+          }
```
Comment (Daemonxiao) [inline core/src/main/scala/com/pingcap/tispark/write/TiBatchWrite.scala:162]: Table check has been done in `TiDBWriter.write`? Is here a duplicate?

File: tikv-client/src/main/java/com/pingcap/tikv/expression/visitor/PartitionLocator.java [hunk 8]
```diff
@@ -0,0 +1,124 @@
...
+    if (rawString.startsWith("'")) {
+      rawString = rawString.substring(1, rawString.length() - 1);
+    }
+    Operator comparisonType = node.getComparisonType();
+
+    switch (comparisonType) {
+      case GREATER_EQUAL:
+        return data.toString().compareTo(rawString) >= 0;
+      case LESS_THAN:
+        return data.toString().compareTo(rawString) < 0;
```
Comment (zhangyangyu) [inline tikv-client/src/main/java/com/pingcap/tikv/expression/visitor/PartitionLocator.java:83]: All compare by string?

File: core/src/main/scala/com/pingcap/tispark/write/TiDBDelete.scala (hunk 3 above)
[the remark this answers is not in the document]
Comment (xuanyu66) [reply core/src/main/scala/com/pingcap/tispark/write/TiDBDelete.scala:107]: https://stackoverflow.com/questions/21185092/apache-spark-map-vs-mappartitions
mappartitions for function with heavy initialization.
Here it's better to use map()

File: core/src/main/scala/com/pingcap/tispark/write/TiBatchWrite.scala (hunk 7 above)
Comment (xuanyu66) [reply core/src/main/scala/com/pingcap/tispark/write/TiBatchWrite.scala:162]: @shiyuhang0 Will this method has another entry rather than TiDBWriter.write()?

File: core/src/main/scala/com/pingcap/tispark/utils/WriteUtil.scala [hunk 9]
```diff
@@ -22,8 +22,9 @@ import com.pingcap.tikv.exception.{
   TiBatchWriteException,
   TiDBConvertException
 }
-import com.pingcap.tikv.key.{CommonHandle, Handle, IndexKey, IntHandle, RowKey}
+import com.pingcap.tikv.key._
```
[the remark this answers is not in the document]
Comment (xuanyu66) [reply core/src/main/scala/com/pingcap/tispark/utils/WriteUtil.scala]: done

File: core/src/main/scala/com/pingcap/tispark/utils/WriteUtil.scala (hunk 6 above)
Comment (xuanyu66) [reply core/src/main/scala/com/pingcap/tispark/utils/WriteUtil.scala:190]: done

File: core/src/main/scala/com/pingcap/tispark/utils/WriteUtil.scala [hunk 10]
```diff
@@ -114,116 +118,152 @@ object WriteUtil {
...
-          encodedValue,
-          isIndex = false,
-          -1,
-          remove = true)
+        generateRecordKVToDelete(wrappedRow, tableId)
       }
     }
   }
 
+  def generateRecordKVToDelete(wrappedRow: WrappedRow, tableId: Long): WrappedEncodedRow = {
```
[the remark this answers is not in the document]
Comment (xuanyu66) [reply core/src/main/scala/com/pingcap/tispark/utils/WriteUtil.scala]: @qidi1 done

File: core/src/main/scala/com/pingcap/tispark/write/TiBatchWrite.scala (hunk 7 above)
Comment (shiyuhang0) [reply core/src/main/scala/com/pingcap/tispark/write/TiBatchWrite.scala:162]: multi-table batch write may entry this method without check
(https://github.com/pingcap/tispark/blob/master/docs/datasource_api_userguide.md#writing-to-multi-tables)

Comment (xuanyu66) [reply core/src/main/scala/com/pingcap/tispark/write/TiBatchWrite.scala:162]: @Daemonxiao So this is necessary

File: core/src/main/scala/com/pingcap/tispark/utils/WriteUtil.scala (hunk 5 above)
Comment (xuanyu66) [reply core/src/main/scala/com/pingcap/tispark/utils/WriteUtil.scala]: done

File: tikv-client/src/main/java/com/pingcap/tikv/partition/PartitionedTable.java [hunk 11]
```diff
@@ -0,0 +1,271 @@
...
+
+  public static PartitionedTable newPartitionTable(
+      TableCommon logicalTable, TiTableInfo tableInfo) {
+    PartitionExpression partitionExpr = generatePartitionExpr(tableInfo);
+
+    List<TiPartitionDef> partitionDefs = tableInfo.getPartitionInfo().getDefs();
+    TableCommon[] physicalTables = new TableCommon[partitionDefs.size()];
+    for (int i = 0; i < partitionDefs.size(); i++) {
+      TiPartitionDef tiPartitionDef = partitionDefs.get(i);
+      TableCommon temp =
```
Comment (zhangyangyu) [inline tikv-client/src/main/java/com/pingcap/tikv/partition/PartitionedTable.java:67]: `temp` seems redundant.

File: tikv-client/src/main/java/com/pingcap/tikv/expression/visitor/PartitionLocator.java [hunk 12]
```diff
@@ -0,0 +1,184 @@
...
+import com.pingcap.tikv.expression.LogicalBinaryExpression.Type;
+import com.pingcap.tikv.meta.TiTableInfo;
+import com.pingcap.tikv.partition.PartitionedTable.PartitionLocatorContext;
+import com.pingcap.tikv.row.Row;
+import com.pingcap.tikv.types.DateType;
+import com.pingcap.tikv.types.IntegerType;
+import java.sql.Date;
+import java.sql.Timestamp;
+
+public class PartitionLocator extends DefaultVisitor<Boolean, PartitionLocatorContext> {
```
Comment (zhangyangyu) [inline tikv-client/src/main/java/com/pingcap/tikv/expression/visitor/PartitionLocator.java:37]: This locator is only for range partition and rangecolumns partition, maybe we can make the name more explicit for this?

**Comment by xuanyu66** [comment]
@zhangyangyu PTAL

File: tikv-client/src/main/java/com/pingcap/tikv/expression/visitor/RangePartitionLocator.java [hunk 13]
```diff
@@ -0,0 +1,183 @@
...
+      switch (comparisonType) {
+        case GREATER_EQUAL:
+          return dataStringValue.compareTo(boundString) >= 0;
+        case LESS_THAN:
+          return dataStringValue.compareTo(boundString) < 0;
+        default:
+          throw new UnsupportedOperationException("Unsupported comparison type: " + comparisonType);
+      }
+    } else if (data instanceof byte[]) {
+      String dataStringValue = new String((byte[]) data);
```
Comment (zhangyangyu) [inline tikv-client/src/main/java/com/pingcap/tikv/expression/visitor/RangePartitionLocator.java:110]: Converting bytes to string involves encoding. This uses the platform default charset. Do we need to specify charset?

Comment (xuanyu66) [reply tikv-client/src/main/java/com/pingcap/tikv/expression/visitor/RangePartitionLocator.java]: @zhangyangyu Agree with you

**Review by zhangyangyu — APPROVED** [review]

File: tikv-client/src/test/java/com/pingcap/tikv/expression/visitor/PartitionLocatorTest.java [hunk 14]
```diff
@@ -0,0 +1,138 @@
...
+    // =
+    assertTrue(locator.evaluateComparison("long".getBytes(), "long", Operator.GREATER_EQUAL));
+    assertFalse(locator.evaluateComparison("long".getBytes(), "long", Operator.LESS_THAN));
+    // >
+    assertTrue(locator.evaluateComparison("long".getBytes(), "loNg", Operator.GREATER_EQUAL));
+    assertFalse(locator.evaluateComparison("long".getBytes(), "long", Operator.LESS_THAN));
+    // <
+    assertFalse(locator.evaluateComparison("LoNg".getBytes(), "loNg", Operator.GREATER_EQUAL));
+    assertTrue(locator.evaluateComparison("LoNg".getBytes(), "loNg", Operator.LESS_THAN));
+  }
```
Comment (shiyuhang0) [inline tikv-client/src/test/java/com/pingcap/tikv/expression/visitor/PartitionLocatorTest.java:137]: does getBytes will always encode use utf-8?

**Review by shiyuhang0 — APPROVED** [review]

File: tikv-client/src/test/java/com/pingcap/tikv/expression/visitor/PartitionLocatorTest.java (hunk 14 above)
Comment (xuanyu66) [reply tikv-client/src/test/java/com/pingcap/tikv/expression/visitor/PartitionLocatorTest.java:137]: Only support with utf-8
