### PR TITLE
Fix timestamp inconsistent

### LINKED ISSUE #682: Timestamp may be inconsistent in different tables in same query.

### PR DESCRIPTION
**Pull request by birdstorm**
Fix #682 #683 
Timestamp may be inconsistent because ResolutionRule may be applied multiple times.

### CODE REVIEW

File: core/src/main/scala/org/apache/spark/sql/extensions/rules.scala [hunk 1]
```diff
@@ -55,22 +56,45 @@ case class TiResolutionRule(getOrCreateTiContext: SparkSession => TiContext)(
         tiSession,
         TiTableReference(dbName, tableName, sizeInBytes),
         meta,
-        Some(ts)
+        Option.apply(ts)
```
Comment (zhexuany) [inline core/src/main/scala/org/apache/spark/sql/extensions/rules.scala]: Why change to `Option.apply`?

Comment (birdstorm) [reply core/src/main/scala/org/apache/spark/sql/extensions/rules.scala]: unintended, i will revert it

File: tikv-client/src/main/java/com/pingcap/tikv/Snapshot.java [hunk 2]
```diff
@@ -38,18 +38,17 @@
...
 import org.tikv.kvproto.Kvrpcpb.KvPair;
 import org.tikv.kvproto.Metapb.Store;
 
 public class Snapshot {
   private final TiTimestamp timestamp;
   private final TiSession session;
-  private final TiConfiguration conf;
 
-  public Snapshot(TiTimestamp timestamp, TiSession session) {
+  public Snapshot(@Nonnull TiTimestamp timestamp, TiSession session) {
```
Comment (marsishandsome) [inline tikv-client/src/main/java/com/pingcap/tikv/Snapshot.java]: what if `timestamp` is null?
how can you ensure `timestamp` is not null?

File: core/src/main/scala/org/apache/spark/sql/extensions/rules.scala [hunk 3]
```diff
@@ -55,22 +56,45 @@ case class TiResolutionRule(getOrCreateTiContext: SparkSession => TiContext)(
...
+          condition = condition.transform {
+            case e @ Exists(p, _, _) =>
+              e.copy(plan = p.transform(applyTimestamp))
+            case ls @ ListQuery(p, _, _, _) =>
+              ls.copy(plan = p.transform(applyTimestamp))
+            case s @ ScalarSubquery(p, _, _) =>
+              s.copy(plan = p.transform(applyTimestamp))
+          }
+        )
+      case p @ Project(projectList, _) =>
```
Comment (marsishandsome) [inline core/src/main/scala/org/apache/spark/sql/extensions/rules.scala]: is there any other cases (except `UnresolvedRelation`, `Filter` and `Project`)?

File: tikv-client/src/main/java/com/pingcap/tikv/Snapshot.java (hunk 2 above)
Comment (birdstorm) [reply tikv-client/src/main/java/com/pingcap/tikv/Snapshot.java]: yes.

File: core/src/main/scala/org/apache/spark/sql/extensions/rules.scala (hunk 3 above)
Comment (birdstorm) [reply core/src/main/scala/org/apache/spark/sql/extensions/rules.scala]: It uses same logic as TiResolutionRule. If it breaks the resolution rule will break first.

Comment (birdstorm) [reply core/src/main/scala/org/apache/spark/sql/extensions/rules.scala]: It uses same logic as TiResolutionRule. If it breaks the resolution rule will break first.

File: core/src/main/spark-2.3/org/apache/spark/sql/TiStrategy.scala [hunk 4]
```diff
@@ -253,6 +250,19 @@ case class TiStrategy(getOrCreateTiContext: SparkSession => TiContext)(sparkSess
       tableScanPlan
     }
 
+    if (tiColumns.isEmpty) {
+      // we cannot send a request with empty columns
+      if (!scanPlan.isIndexScan) {
```
Comment (zhexuany) [inline core/src/main/spark-2.3/org/apache/spark/sql/TiStrategy.scala]: invert the logic here for better readability?

File: core/src/main/spark-2.4/org/apache/spark/sql/TiStrategy.scala [hunk 5]
```diff
@@ -253,6 +250,19 @@ case class TiStrategy(getOrCreateTiContext: SparkSession => TiContext)(sparkSess
       tableScanPlan
     }
 
+    if (tiColumns.isEmpty) {
```
Comment (zhexuany) [inline core/src/main/spark-2.4/org/apache/spark/sql/TiStrategy.scala]: Since it is used in both spark 2.3 and spark 2.4, maybe we can wrap this logic into a function?

File: tikv-client/src/main/java/com/pingcap/tikv/meta/TiDAGRequest.java [hunk 6]
```diff
@@ -369,7 +370,9 @@ else if (col.getColumnInfo().isPrimaryKey() && tableInfo.isPkHandle()) {
       }
 
       dagRequestBuilder.addExecutors(executorBuilder.setTblScan(tblScanBuilder));
+    }
 
+    if (!buildIndexScan || !isDoubleRead()) {
```
Comment (zhexuany) [inline tikv-client/src/main/java/com/pingcap/tikv/meta/TiDAGRequest.java]: It should have some comments.

Comment (birdstorm) [reply tikv-client/src/main/java/com/pingcap/tikv/meta/TiDAGRequest.java]: sure.
