### PR TITLE
Fix encoder v2 with type convertion and set default batch write version to v2

### LINKED ISSUE #1622: [BUG] Fail to batch write decimal type with conversion in new row format
**Describe the bug**
batch write with decimal type will fail when using new row format

**Spark and TiSpark version info**

### PR DESCRIPTION
**Pull request by birdstorm**
Fix #1622 

Also fixes similar problems in decimal/string/enum conversions.

### Check List 

Tests 

 - Unit test
 - Integration test

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to be included in the release note

### CODE REVIEW

File: tikv-client/src/main/java/com/pingcap/tikv/codec/RowEncoderV2.java [hunk 1]
```diff
@@ -316,12 +316,19 @@ private void encodeTimestamp(CodecDataOutput cdo, Object value, DateTimeZone tz)
   }
 
   private void encodeDecimal(CodecDataOutput cdo, Object value) {
-    MyDecimal dec = new MyDecimal();
-    BigDecimal decimal = (BigDecimal) value;
-    int prec = decimal.precision();
-    int frac = decimal.scale();
-    dec.fromString(((BigDecimal) value).toPlainString());
-    DecimalCodec.writeDecimal(cdo, dec, prec, frac);
+    if (value instanceof MyDecimal) {
```
Comment (birdstorm) [inline tikv-client/src/main/java/com/pingcap/tikv/codec/RowEncoderV2.java:319]: fyi @marsishandsome

File: tikv-client/src/main/java/com/pingcap/tikv/codec/RowEncoderV2.java [hunk 2]
```diff
@@ -315,6 +319,16 @@ private void encodeTimestamp(CodecDataOutput cdo, Object value, DateTimeZone tz)
     }
   }
 
+  private void encodeString(CodecDataOutput cdo, Object value) {
```
Comment (birdstorm) [inline tikv-client/src/main/java/com/pingcap/tikv/codec/RowEncoderV2.java:322]: string logic

File: tikv-client/src/main/java/com/pingcap/tikv/codec/RowEncoderV2.java [hunk 3]
```diff
@@ -290,9 +288,15 @@ private void encodeDouble(CodecDataOutput cdo, Object value) {
 
   private void encodeBit(CodecDataOutput cdo, Object value) {
     long s = 0;
-    for (byte b : (byte[]) value) {
-      s <<= 8;
-      s |= b;
+    if (value instanceof Long) {
```
Comment (birdstorm) [inline tikv-client/src/main/java/com/pingcap/tikv/codec/RowEncoderV2.java:291]: bit logic

File: tikv-client/src/main/java/com/pingcap/tikv/codec/RowEncoderV2.java [hunk 4]
```diff
@@ -332,8 +346,14 @@ private void encodeDecimal(CodecDataOutput cdo, Object value) {
   }
 
   private void encodeEnum(CodecDataOutput cdo, Object value, List<String> elems) {
-    int val = EnumCodec.parseEnumName((String) value, elems);
-    encodeInt(cdo, val);
+    if (value instanceof Integer) {
```
Comment (birdstorm) [inline tikv-client/src/main/java/com/pingcap/tikv/codec/RowEncoderV2.java:349]: enum logic

File: tikv-client/src/main/java/com/pingcap/tikv/codec/RowEncoderV2.java [hunk 5]
```diff
@@ -290,9 +288,15 @@ private void encodeDouble(CodecDataOutput cdo, Object value) {
...
+    } else if (value instanceof byte[]) {
+      for (byte b : (byte[]) value) {
+        s <<= 8;
+        s |= b;
+      }
+    } else {
+      throw new CodecException("invalid bytes type " + value.getClass());
     }
     encodeInt(cdo, s);
   }
```
Comment (birdstorm) [inline tikv-client/src/main/java/com/pingcap/tikv/codec/RowEncoderV2.java:302]: bit logic here. @marsishandsome

File: tikv-client/src/main/java/com/pingcap/tikv/codec/RowEncoderV2.java [hunk 6]
```diff
@@ -315,18 +319,41 @@ private void encodeTimestamp(CodecDataOutput cdo, Object value, DateTimeZone tz)
...
 
+  private void encodeString(CodecDataOutput cdo, Object value) {
+    if (value instanceof byte[]) {
+      cdo.write((byte[]) value);
+    } else if (value instanceof String) {
+      cdo.write(((String) value).getBytes(StandardCharsets.UTF_8));
+    } else {
+      throw new CodecException("invalid string type " + value.getClass());
+    }
+  }
```
Comment (birdstorm) [inline tikv-client/src/main/java/com/pingcap/tikv/codec/RowEncoderV2.java:330]: String logic here.

File: tikv-client/src/main/java/com/pingcap/tikv/codec/RowEncoderV2.java [hunk 7]
```diff
@@ -315,18 +319,41 @@ private void encodeTimestamp(CodecDataOutput cdo, Object value, DateTimeZone tz)
...
+      MyDecimal dec = new MyDecimal();
+      BigDecimal decimal = (BigDecimal) value;
+      int prec = decimal.precision();
+      int frac = decimal.scale();
+      dec.fromString(((BigDecimal) value).toPlainString());
+      DecimalCodec.writeDecimal(cdo, dec, prec, frac);
+    } else {
+      throw new CodecException("invalid decimal type " + value.getClass());
+    }
   }
```
Comment (birdstorm) [inline tikv-client/src/main/java/com/pingcap/tikv/codec/RowEncoderV2.java:346]: decimal logic here

File: tikv-client/src/main/java/com/pingcap/tikv/codec/RowEncoderV2.java [hunk 8]
```diff
@@ -315,18 +319,41 @@ private void encodeTimestamp(CodecDataOutput cdo, Object value, DateTimeZone tz)
...
-    encodeInt(cdo, val);
+    if (value instanceof Integer) {
+      encodeInt(cdo, (int) value);
+    } else if (value instanceof String) {
+      int val = EnumCodec.parseEnumName((String) value, elems);
+      encodeInt(cdo, val);
+    } else {
+      throw new CodecException("invalid enum type " + value.getClass());
+    }
   }
```
Comment (birdstorm) [inline tikv-client/src/main/java/com/pingcap/tikv/codec/RowEncoderV2.java:357]: enum logic here
