### PR TITLE
com.pingcap,tikv.key : bug fix reslove bug of cannot encode row key with non-long type ref: #2290

### LINKED ISSUE #2290: [BUG] TiExpressionException: Cannot encode row key with non-long type
**Describe the bug**

create table with `BITINT UNSIGNED` primary key, when run sample SQL with range predicate, i will meet `TiExpressionException: Cannot encode row key with non-long type`. 

**What did you do**

first , create sample table in mysql client.
```
CREATE TABLE `test` (
  `id` BIGINT(20) UNSIGNED  NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `age` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```

than , run sample sql with range predicate, than will meet the exception. like 

> ./bin/spark-sql --jars ~/tispark-assembly-2.4.3-scala_2.11.jar

> SELECT * FROM test.test WHERE id >= 0 LIMIT 10;

**What happens instead**

full stack:
```
com.pingcap.tikv.exception.TiExpressionException: Cannot encode row key with non-long type
    at com.pingcap.tikv.key.RowKey.toRowKey(RowKey.java:64)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.buildTableScanKeyRangePerId(TiKVScanAnalyzer.java:321)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.lambda$buildTableScanKeyRangeWithIds$0(TiKVScanAnalyzer.java:349)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.buildTableScanKeyRangeWithIds(TiKVScanAnalyzer.java:347)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.buildTableScanKeyRange(TiKVScanAnalyzer.java:376)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.buildIndexScan(TiKVScanAnalyzer.java:273)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.buildTableScan(TiKVScanAnalyzer.java:228)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.buildTiDAGReq(TiKVScanAnalyzer.java:162)
    at org.apache.spark.sql.TiStrategy.filterToDAGRequest(TiStrategy.scala:295)
    at org.apache.spark.sql.TiStrategy.pruneFilterProject(TiStrategy.scala:417)
    at org.apache.spark.sql.TiStrategy.pruneTopNFilterProject(TiStrategy.scala:320)
    at org.apache.spark.sql.TiStrategy.collectLimit(TiStrategy.scala:327)
    at org.apache.spark.sql.TiStrategy.org$apache$spark$sql$TiStrategy$$doPlan(TiStrategy.scala:573)
    at org.apache.spark.sql.TiStrategy$$anonfun$apply$1.applyOrElse(TiStrategy.scala:119)
    at org.apache.spark.sql.TiStrategy$$anonfun$apply$1.applyOrElse(TiStrategy.scala:117)
    at scala.PartialFunction$Lifted.apply(PartialFunction.scala:223)
    at scala.PartialFunction$Lifted.apply(PartialFunction.scala:219)
    at org.apache.spark.sql.catalyst.trees.TreeNode.collectFirst(TreeNode.scala:175)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode.collectFirst(TreeNode.scala:175)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode.collectFirst(TreeNode.scala:175)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode.collectFirst(TreeNode.scala:175)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode.collectFirst(TreeNode.scala:175)
    at org.apache.spark.sql.TiStrategy.apply(TiStrategy.scala:117)
    at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:63)
    at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:63)
    at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
    at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
    at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
    at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
    at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:73)
    at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:69)
    at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:78)
    at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:78)
    at org.apache.spark.sql.execution.QueryExecution$$anonfun$toString$3.apply(QueryExecution.scala:209)
    at org.apache.spark.sql.execution.QueryExecution$$anonfun$toString$3.apply(QueryExecution.scala:209)
    at org.apache.spark.sql.execution.QueryExecution.stringOrError(QueryExecution.scala:101)
    at org.apache.spark.sql.execution.QueryExecution.toString(QueryExecution.scala:209)
    at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:77)
    at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:145)
    at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
    at org.apache.spark.sql.hive.thriftserver.SparkSQLDriver.run(SparkSQLDriver.scala:71)
    at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.processCmd(SparkSQLCLIDriver.scala:393)
    at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:376)
    at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver$.main(SparkSQLCLIDriver.scala:278)
    at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.main(SparkSQLCLIDriver.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
    at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:866)
    at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:184)
    at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:212)
    at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
    at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:941)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:950)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
com.pingcap.tikv.exception.TiExpressionException: Cannot encode row key with non-long type
    at com.pingcap.tikv.key.RowKey.toRowKey(RowKey.java:64)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.buildTableScanKeyRangePerId(TiKVScanAnalyzer.java:321)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.lambda$buildTableScanKeyRangeWithIds$0(TiKVScanAnalyzer.java:349)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.buildTableScanKeyRangeWithIds(TiKVScanAnalyzer.java:347)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.buildTableScanKeyRange(TiKVScanAnalyzer.java:376)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.buildIndexScan(TiKVScanAnalyzer.java:273)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.buildTableScan(TiKVScanAnalyzer.java:228)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.buildTiDAGReq(TiKVScanAnalyzer.java:162)
    at org.apache.spark.sql.TiStrategy.filterToDAGRequest(TiStrategy.scala:295)
    at org.apache.spark.sql.TiStrategy.pruneFilterProject(TiStrategy.scala:417)
    at org.apache.spark.sql.TiStrategy.pruneTopNFilterProject(TiStrategy.scala:320)
    at org.apache.spark.sql.TiStrategy.collectLimit(TiStrategy.scala:327)
    at org.apache.spark.sql.TiStrategy.org$apache$spark$sql$TiStrategy$$doPlan(TiStrategy.scala:573)
    at org.apache.spark.sql.TiStrategy$$anonfun$apply$1.applyOrElse(TiStrategy.scala:119)
    at org.apache.spark.sql.TiStrategy$$anonfun$apply$1.applyOrElse(TiStrategy.scala:117)
    at scala.PartialFunction$Lifted.apply(PartialFunction.scala:223)
    at scala.PartialFunction$Lifted.apply(PartialFunction.scala:219)
    at org.apache.spark.sql.catalyst.trees.TreeNode.collectFirst(TreeNode.scala:175)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode.collectFirst(TreeNode.scala:175)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode.collectFirst(TreeNode.scala:175)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode.collectFirst(TreeNode.scala:175)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode.collectFirst(TreeNode.scala:175)
    at org.apache.spark.sql.TiStrategy.apply(TiStrategy.scala:117)
    at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:63)
    at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:63)
    at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
    at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
    at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
    at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
    at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:73)
    at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:69)
    at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:78)
    at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:78)
    at org.apache.spark.sql.execution.QueryExecution$$anonfun$toString$3.apply(QueryExecution.scala:209)
    at org.apache.spark.sql.execution.QueryExecution$$anonfun$toString$3.apply(QueryExecution.scala:209)
    at org.apache.spark.sql.execution.QueryExecution.stringOrError(QueryExecution.scala:101)
    at org.apache.spark.sql.execution.QueryExecution.toString(QueryExecution.scala:209)
    at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:77)
    at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:145)
    at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
    at org.apache.spark.sql.hive.thriftserver.SparkSQLDriver.run(SparkSQLDriver.scala:71)
    at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.processCmd(SparkSQLCLIDriver.scala:393)
    at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:376)
    at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver$.main(SparkSQLCLIDriver.scala:278)
    at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.main(SparkSQLCLIDriver.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
    at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:866)
    at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:184)
    at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:212)
    at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
    at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:941)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:950)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Spark and TiSpark version info**

spark version : spark2.4.0
tispark : 2.4.3-scala_2.11

### PR DESCRIPTION
**Pull request by qidi1**
Signed-off-by: qidi1 <1083369179@qq.com>

### What problem does this PR solve? 
Issue Link
* close #2290
when create table with BITINT UNSIGNED primary key,and run a sql which has range in primary key.A exception will happend.

### What is changed and how it works?
We have a special treatment for BIGINT UNSIGNED. The BIGINT UNSIGNED is cut into two ranges to discuss, one range is [0,MaxInt64] and one is [MaxInt64+1,MaxUint64].

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change

Side effects

Related changes

### CODE REVIEW

**Comment by qidi1** [comment]
## Detailed Design

We have a special treatment for BIGINT UNSIGNED. The BIGINT UNSIGNED is cut into two ranges to discuss, one range is [0,MaxInt64] and one is [MaxInt64+1,MaxUint64].

The detail design is divided into two main parts:

1. Separate treatment of [0,MaxInt64]and [MaxInt64+1,MaxUnit64].
1. Special treatment for  do not having upper bound or lower bound. 

### Separate treatment of [0,MaxInt64]and [MaxInt64+1,MaxUnit64]

1. StartKey

   1. When  StartKey small than MaxInt64

      ```java
      startKeys[0]=RowKey.toRowKey(id,new IntHandle(bigDecimal.longValue()));
      startKeys[1]=RowKey.toRowKey(id,new IntHandle(max.longValue()+1));
      if (r.lowerBoundType().equals(BoundType.OPEN)) {
           startKeys[0] = startKeys[0].next();
      }
      ```

      ​	`StartKeys[0]` is request StartKey,`StartKey[1]` is MaxInt64+1.

   2. When StartKey bigger than MaxInt64

      ```java
      startKeys[0]=RowKey.toRowKey(id,new IntHandle(max.longValue()));
      startKeys[1]=RowKey.toRowKey(id,new IntHandle(bigDecimal.longValue()));
      startKeys[0]=startKeys[0].next();
      if (r.lowerBoundType().equals(BoundType.OPEN)) {
             startKeys[1] = startKeys[1].next();
      }
      ```

      ​	`StartKey[0]` will be bigger than MaxInt64,`StartKeys[1]` is request StartKey.

2. EndKey

   1. When  EndKey small than MaxInt64

      ```java
      endKeys[0]=RowKey.toRowKey(id,new IntHandle(bigDecimal.longValue()));
      endKeys[1]=RowKey.toRowKey(id,new IntHandle(max.longValue()+1));
      if (r.upperBoundType().equals(BoundType.CLOSED)) {
          endKeys[0] = endKeys[0].next();
      }
      ```

      ​	`EndKeys[0]` is request EndKey,`EndKeys[1]` is MaxInt64+1.Since EndKey is open interval,the MaxInt64 will not appears in our request.

   2. When EndKey bigger than MaxInt64

      ```java
      startKeys[0]=RowKey.toRowKey(id,new IntHandle(max.longValue()));
      startKeys[1]=RowKey.toRowKey(id,new IntHandle(bigDecimal.longValue()));
      startKeys[0]=startKeys[0].next();
      if (r.lowerBoundType().equals(BoundType.OPEN)) {
             startKeys[1] = startKeys[1].next();
      }
      ```

      ​		`EndKeys[1]` is request EndKey,`EndKeys[0]` is bigger than MaxInt64+1,

   ### Special treatment for  do not having upper bound or lower bound

   when we do not having upper bound or lower bound,we have to add some special treatment of it.

   1. no upper bound and no lower bound:

      do same as before.

   2. having lower bound but no upper bound:

      1. not `BigDecimal`:

         do same as before

      2. `BigDecimal`:

         ```java
         endKeys[0]=RowKey.toRowKey(id,new IntHandle(Long.MAX_VALUE));
         endKeys[1]=RowKey.createBeyondMax(id);
         // since range is left-closed and right-open interval,
         // we have to use next to inclusive Long.MAX_VALUE.
         endKeys[0]=endKeys[0].next();
         ```

   3. no lower bound but upper bound:

      1. not `BigDecimal`:

         do same as before.

      2. `BigDecimal`:

         The StartKeys[0] should be -INF,StartKeys[1] should be MaxInt64+1.

         I feel hard to know the type of data before come to upper bound,so adding StartKeys[1] has been put off until processing upper bound. 

         ```java
         if(bigDecimal.compareTo(max)>0){
              endKeys[0]=RowKey.toRowKey(id,new IntHandle(max.longValue()));
              endKeys[1]=RowKey.toRowKey(id,new IntHandle(bigDecimal.longValue()));
              endKeys[0]=endKeys[0].next();
               if (r.upperBoundType().equals(BoundType.CLOSED)) {
                    endKeys[1] = endKeys[1].next();
               }
         }else{
               endKeys[0]=RowKey.toRowKey(id,new IntHandle(bigDecimal.longValue()));
               endKeys[1]=RowKey.toRowKey(id,new IntHandle(max.longValue()+1));
                if (r.upperBoundType().equals(BoundType.CLOSED)) {
                       endKeys[0] = endKeys[0].next();
                 }
          startKeys[1]=RowKey.toRowKey(id,new IntHandle(max.longValue()+1));
         ```

File: tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java [hunk 1]
```diff
@@ -297,47 +297,109 @@ TiKVScanPlan buildIndexScan(
     }
   }
 
-  private Pair<Key, Key> buildTableScanKeyRangePerId(long id, IndexRange ir) {
-    Key startKey;
-    Key endKey;
+  private Pair<Pair<Key,Key>,Optional<Pair<Key,Key>>> buildTableScanKeyRangePerId(long id, IndexRange ir) {
+    List<Key> startKeys=new ArrayList<>(2);
```
Comment (xuanyu66) [inline tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java:301]: Pair<Key, Key> signedRange

File: tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java [hunk 2]
```diff
@@ -297,47 +296,106 @@ TiKVScanPlan buildIndexScan(
...
       checkArgument(key instanceof TypedKey, "Table scan key range must be typed key");
-      TypedKey typedKey = (TypedKey) key;
-      startKey = RowKey.toRowKey(id, typedKey);
-      endKey = startKey.next();
+      Object obj = ((TypedKey) key).getValue();
+      if(obj instanceof Long){
+        signedStartKey=RowKey.toRowKey(id,new IntHandle((long)obj));
+        signedEndKey=signedStartKey.next();
+      }else if (obj instanceof BigDecimal){
+        BigDecimal bigDecimal=(BigDecimal)obj;
```
Comment (xuanyu66) [inline tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java:313]: Do we need to check if obj <= uint64.max?

File: tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java [hunk 3]
```diff
@@ -297,47 +296,106 @@ TiKVScanPlan buildIndexScan(
...
       Key key = ir.getAccessKey();
       checkArgument(key instanceof TypedKey, "Table scan key range must be typed key");
-      TypedKey typedKey = (TypedKey) key;
-      startKey = RowKey.toRowKey(id, typedKey);
-      endKey = startKey.next();
+      Object obj = ((TypedKey) key).getValue();
+      if(obj instanceof Long){
+        signedStartKey=RowKey.toRowKey(id,new IntHandle((long)obj));
+        signedEndKey=signedStartKey.next();
+      }else if (obj instanceof BigDecimal){
```
Comment (xuanyu66) [inline tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java:312]: Have you checked whether obj is BigDecimal when range is unsignedRange?

**Comment by xuanyu66** [comment]
Check this https://github.com/pingcap/tispark/pull/2291#issuecomment-1108390798, you should also fix this bug

File: core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala [hunk 4]
```diff
@@ -600,7 +600,24 @@ class IssueTestSuite extends BaseTiSparkTest {
...
+    }
+    tidbStmt.execute("DROP TABLE IF EXISTS `t1`")
+    tidbStmt.execute("""
+                       |CREATE TABLE `t1` (
+                       |  `a` BIGINT(20) UNSIGNED  NOT NULL AUTO_INCREMENT,
+                       |  `b` varchar(255) NOT NULL,
+                       |  `c` varchar(255) DEFAULT NULL,
+                       |  PRIMARY KEY (`a`)
+                       |) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin""".stripMargin)
+    tidbStmt.execute("INSERT INTO t1 VALUES (1, 'aa', 'aa'),(2, 'aa', 'aa')")
```
Comment (xuanyu66) [inline core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala:616]: This test is too simple, we should also test boundary conditions

File: core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala [hunk 5]
```diff
@@ -600,7 +600,24 @@ class IssueTestSuite extends BaseTiSparkTest {
     assert(df.count() >= size)
   }
 
-  override def afterAll(): Unit =
+  // https://github.com/pingcap/tispark/issues/2290
+  test("fix cannot encode row key with non-long type") {
+    if (enableTiFlashTest) {
```
Comment (xuanyu66) [inline core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala:605]: Why should we skip?

File: core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala [hunk 6]
```diff
@@ -600,7 +600,24 @@ class IssueTestSuite extends BaseTiSparkTest {
...
+    tidbStmt.execute("DROP TABLE IF EXISTS `t1`")
+    tidbStmt.execute("""
+                       |CREATE TABLE `t1` (
+                       |  `a` BIGINT(20) UNSIGNED  NOT NULL AUTO_INCREMENT,
+                       |  `b` varchar(255) NOT NULL,
+                       |  `c` varchar(255) DEFAULT NULL,
+                       |  PRIMARY KEY (`a`)
+                       |) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin""".stripMargin)
+    tidbStmt.execute("INSERT INTO t1 VALUES (1, 'aa', 'aa'),(2, 'aa', 'aa')")
+    explainTestAndCollect("SELECT * FROM t1 WHERE a>= 0 LIMIT 10")
```
Comment (xuanyu66) [inline core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala:617]: How can we check pushdown is successful?

**Review by xuanyu66 — CHANGES_REQUESTED** [review]

**Comment by xuanyu66** [comment]
@shiyuhang0  PTAL

**Comment by xuanyu66** [comment]
@qidi1 check the CI, it seems like some tests failed

File: tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java (hunk 2 above)
Comment (qidi1) [reply tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java:313]: > Do we need to check if obj <= uint64.max?

```java
 protected Object decodeNotNull(int flag, CodecDataInput cdi) {
    long ret;
    switch (flag) {
       ...
      case Codec.UINT_FLAG:
        ret = IntegerCodec.readULong(cdi);
        break;
        ...
    }
    if (isUnsignedLong()) {
      return unsignedValueOf(ret);
    }
    return ret;
  }
```
the value first convert to long and then convert to bigDecimal. So obj will never beyond uint64.max

File: tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java (hunk 3 above)
Comment (qidi1) [reply tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java:312]: > Have you checked whether obj is BigDecimal when range is unsignedRange?

```java
 protected Object decodeNotNull(int flag, CodecDataInput cdi) {
    long ret;
    switch (flag) {
       ...
      case Codec.UINT_FLAG:
        ret = IntegerCodec.readULong(cdi);
        break;
        ...
    }
    if (isUnsignedLong()) {
      return unsignedValueOf(ret);
    }
    return ret;
  }
public boolean isUnsignedLong() {
    return tp == MySQLType.TypeLonglong && isUnsigned();
  }
```
Only unsignedLong will convert to bigDemical

File: core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala (hunk 4 above)
Comment (qidi1) [reply core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala]: Add more situations

File: core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala (hunk 6 above)
Comment (qidi1) [reply core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala]: Add check of pushdown

File: tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java [hunk 7]
```diff
@@ -297,47 +297,116 @@ TiKVScanPlan buildIndexScan(
...
+        if (obj instanceof Long) {
+          signedEndKey = RowKey.toRowKey(id, new IntHandle((long) obj));
+          if (r.upperBoundType().equals(BoundType.CLOSED)) {
+            signedEndKey = signedEndKey.nextPrefix();
+          }
+        } else if (obj instanceof BigDecimal) {
+          isUnsignedLong = true;
+          BigDecimal bigDecimal = (BigDecimal) obj;
+          if (!r.hasLowerBound()) {
+            unsignedStartKey = RowKey.toRowKey(id, new IntHandle(max.longValue() + 1));
```
Comment (shiyuhang0) [inline tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java:385]: why +1

File: tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java [hunk 8]
```diff
@@ -297,47 +297,116 @@ TiKVScanPlan buildIndexScan(
...
-        if (r.upperBoundType().equals(BoundType.CLOSED)) {
-          endKey = endKey.next();
+        /**
+         * {@link com.pingcap.tikv.types.IntegerType#decodeNotNull(int, CodecDataInput)}
+         */
+        Object obj = r.upperEndpoint().getValue();
+        if (obj instanceof Long) {
+          signedEndKey = RowKey.toRowKey(id, new IntHandle((long) obj));
+          if (r.upperBoundType().equals(BoundType.CLOSED)) {
+            signedEndKey = signedEndKey.nextPrefix();
```
Comment (shiyuhang0) [inline tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java:379]: same as before

File: tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java [hunk 9]
```diff
@@ -297,47 +297,116 @@ TiKVScanPlan buildIndexScan(
...
     } else if (ir.hasRange()) {
       checkArgument(
           !ir.hasAccessKey(), "Table scan must have one and only one access condition / point");
       Range<TypedKey> r = ir.getRange();
-
+      BigDecimal max = new BigDecimal(Long.MAX_VALUE);
       if (!r.hasLowerBound()) {
         // -INF
-        startKey = RowKey.createMin(id);
+        signedStartKey = RowKey.createMin(id);
```
Comment (shiyuhang0) [inline tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java:328]: signedStartKey need to be 0 when unsigned long. 
for example : id < 2 => [0,2)

**Review by shiyuhang0 — CHANGES_REQUESTED** [review]

File: core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala [hunk 10]
```diff
@@ -112,6 +116,48 @@ class LogicalPlanTestSuite extends BasePlanTest {
...
+        String]("9223372036854775808", "9223372036854775809"),
+      "SELECT * FROM t1 WHERE a<=9223372036854775808" -> List[String]("9223372036854775808"),
+      "SELECT * FROM t1 WHERE a <= 9223372036854775807" -> List[String]("9223372036854775807"),
+      "SELECT * FROM t1 WHERE a <= 9223372036854775808" -> List[String]("9223372036854775808"))
+    situations.foreach((situation) => {
+      val sql = situation._1
+      val exception = situation._2
+      val df = spark.sql(sql)
+      val filter = extractDAGRequests(df).head.getDowngradeFilters
+      if (!filter.size().equals(exception.size)) {
```
Comment (shiyuhang0) [inline core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala:148]: DowngradeFilters is not the filter that will be pushed down.

File: tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java [hunk 11]
```diff
@@ -30,10 +30,7 @@
 import com.pingcap.tikv.expression.Expression;
 import com.pingcap.tikv.expression.PartitionPruner;
 import com.pingcap.tikv.expression.visitor.IndexMatcher;
-import com.pingcap.tikv.key.IndexScanKeyRangeBuilder;
-import com.pingcap.tikv.key.Key;
-import com.pingcap.tikv.key.RowKey;
-import com.pingcap.tikv.key.TypedKey;
+import com.pingcap.tikv.key.*;
```
Comment (xuanyu66) [inline tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java:33]: Disable wild import
https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html#disable-wildcard-imports

File: core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala [hunk 12]
```diff
@@ -17,6 +17,7 @@
 package org.apache.spark.sql
 
 import com.pingcap.tispark.TiConfigConst
+import com.pingcap.tispark.utils.TiUtil
```
[the remark this answers is not in the document]
Comment (qidi1) [reply core/src/test/scala/org/apache/spark/sql/IssueTestSuite.scala]: OK.Rmove

File: core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala [hunk 13]
```diff
@@ -112,6 +116,48 @@ class LogicalPlanTestSuite extends BasePlanTest {
...
+      "SELECT * FROM t1 WHERE a >= 0 and a <= 9223372036854775807" -> List[String](
+        "0",
+        "9223372036854775807"),
+      "SELECT * FROM t1 WHERE a >= 0 and a<= 9223372036854775808" -> List[String](
+        "0",
+        "9223372036854775808"),
+      "SELECT * FROM t1 WHERE a >= 0" -> List[String]("0"),
+      "SELECT * FROM t1 WHERE a >= 9223372036854775808 and a<=9223372036854775809" -> List[
+        String]("9223372036854775808", "9223372036854775809"),
+      "SELECT * FROM t1 WHERE a<=9223372036854775808" -> List[String]("9223372036854775808"),
```
[the remark this answers is not in the document]
Comment (qidi1) [reply core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala]: already format

File: core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala (hunk 10 above)
Comment (qidi1) [reply core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala]: Change to see if the query results match the requirements

File: tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java (hunk 9 above)
Comment (qidi1) [reply tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java]: changed,when no upper bound,signedStartKey will be zero

File: core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala [hunk 14]
```diff
@@ -113,47 +113,56 @@ class LogicalPlanTestSuite extends BasePlanTest {
...
+        "0",
+        "9223372036854775807"),
+      "SELECT * FROM t1 " -> List[String](
+        "0",
+        "9223372036854775807",
+        "9223372036854775808",
+        "18446744073709551615"))
     situations.foreach((situation) => {
       val sql = situation._1
       val exception = situation._2
```
Comment (xuanyu66) [inline core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala:162]: expectation, not exception QAQ

File: tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java (hunk 8 above)
Comment (qidi1) [reply tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java]: change to when not unsigned long or other type of long will throw exception

File: tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java [hunk 15]
```diff
@@ -297,47 +297,116 @@ TiKVScanPlan buildIndexScan(
...
+       */
+      Object obj = ((TypedKey) key).getValue();
+      if (obj instanceof Long) {
+        signedStartKey = RowKey.toRowKey(id, new IntHandle((long) obj));
+        signedEndKey = signedStartKey.next();
+      } else if (obj instanceof BigDecimal) {
+        BigDecimal bigDecimal = (BigDecimal) obj;
+        signedStartKey = RowKey.toRowKey(id, new IntHandle(bigDecimal.longValue()));
+        signedEndKey = signedStartKey.nextPrefix();
+      }
```
[the remark this answers is not in the document]
Comment (qidi1) [reply tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java:318]: change to when not unsigned long or other type of long will throw exception

File: core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala (hunk 14 above)
Comment (qidi1) [reply core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala]: OK.changed

File: core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala [hunk 16]
```diff
@@ -120,6 +128,174 @@ class LogicalPlanTestSuite extends BasePlanTest {
...
+      for (x <- value.indices) {
+        assert(value(x)(0).toString.equals(valueExpectations(i)(x)))
+      }
+      if (rangeFilter.size() == 1) {
+        println(i)
+        assert(rangeFilter.get(0).toString.equals(expressionExpectations(i).toString))
+      }
+    }
+  }
+
```
Comment (shiyuhang0) [inline core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala:298]: add test:
- `SELECT a FROM t1 WHERE a >= 9223372036854775808 and a<=9223372036854775809`
- `SELECT a FROM t1 WHERE a >= 9223372036854775808`

File: core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala [hunk 17]
```diff
@@ -45,7 +52,8 @@ class LogicalPlanTestSuite extends BasePlanTest {
 
   test("fix Residual Filter containing wrong info") {
     val df = spark
-      .sql("select * from full_data_type_table where tp_mediumint > 0 order by tp_int")
+      .sql("select * from full_data_type_table where tp_mediumint>0 order by tp_int")
+    df.explain(true)
```
[the remark this answers is not in the document]
Comment (qidi1) [reply core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala:55]: fault operator

File: core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala [hunk 18]
```diff
@@ -120,6 +128,174 @@ class LogicalPlanTestSuite extends BasePlanTest {
     }
   }
 
+  // https://github.com/pingcap/tispark/issues/2290
+  test("fix cannot encode row key with non-long type") {
+    val tiSparkTeleInfo = TiSparkTeleInfo.getTiSparkTeleInfo()
+    val version = tiSparkTeleInfo.get("tidb_version")
```
[the remark this answers is not in the document]
Comment (qidi1) [reply core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala:133]: > get version info from `StoreVersion`, get from telemetry is not a good chooise

OK,changed

File: core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala (hunk 16 above)
Comment (qidi1) [reply core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala:261]: > add test:
> 
> * `SELECT a FROM t1 WHERE a >= 9223372036854775808 and a<=9223372036854775809`
> * `SELECT a FROM t1 WHERE a >= 9223372036854775808`

add test

File: core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala [hunk 19]
```diff
@@ -120,6 +128,174 @@ class LogicalPlanTestSuite extends BasePlanTest {
...
+        val startKey = KeyUtils.formatBytesUTF8(range.get(x).getStart.toByteArray)
+        val endKey = KeyUtils.formatBytesUTF8(range.get(x).getEnd.toByteArray)
+        assert(startKey.equals(rowKeyExpectations(i)(2 * x)))
+        assert(endKey.equals(rowKeyExpectations(i)(2 * x + 1)))
+      }
+      for (x <- value.indices) {
+        assert(value(x)(0).toString.equals(valueExpectations(i)(x)))
+      }
+      if (rangeFilter.size() == 1) {
+        println(i)
```
[the remark this answers is not in the document]
Comment (qidi1) [reply core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala]: delte

**Review by xuanyu66 — CHANGES_REQUESTED** [review]

File: tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java [hunk 20]
```diff
@@ -305,47 +307,118 @@ TiKVScanPlan buildIndexScan(
...
     }
-    return new Pair<>(startKey, endKey);
+    return new ScanRange(signedStartKey, signedEndKey);
+  }
+
+  private ScanRange buildTableScanUnsignedKeyRangePerId(long id, IndexRange ir) {
+    BigDecimal max = new BigDecimal(Long.MAX_VALUE);
+    Key signedStartKey = RowKey.toRowKey(id, new IntHandle(max.longValue())).nextPrefix();
+    Key unsignedStartKey = RowKey.toRowKey(id, new IntHandle(max.longValue() + 1));
+    Key signedEndKey = RowKey.toRowKey(id, new IntHandle(max.longValue())).nextPrefix();
```
[the remark this answers is not in the document]
Comment (qidi1) [reply tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java]: Because signed means the end of sign value, unsigned means the start of unsigned value

File: tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java [hunk 21]
```diff
@@ -305,47 +307,118 @@ TiKVScanPlan buildIndexScan(
...
     } else {
       throw new TiClientInternalException("Empty access conditions");
     }
-    return new Pair<>(startKey, endKey);
+    return new ScanRange(signedStartKey, signedEndKey);
+  }
+
+  private ScanRange buildTableScanUnsignedKeyRangePerId(long id, IndexRange ir) {
+    BigDecimal max = new BigDecimal(Long.MAX_VALUE);
+    Key signedStartKey = RowKey.toRowKey(id, new IntHandle(max.longValue())).nextPrefix();
```
[the remark this answers is not in the document]
Comment (qidi1) [reply tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java]: > I can't understand these four initial values, it's wired

These initial values reduce the subsequent judgments.
For example, when unsigned endKey is greater than long.max. We do not need to judge whether the signed startKey is less than long.max to decide whether we need to change the value of the signed endKey.

File: tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java [hunk 22]
```diff
@@ -305,47 +307,118 @@ TiKVScanPlan buildIndexScan(
...
+        } else {
+          signedStartKey = RowKey.toRowKey(id, new IntHandle(startValue.longValue()));
+          if (r.lowerBoundType().equals(BoundType.OPEN)) {
+            signedStartKey = signedStartKey.nextPrefix();
+          }
+        }
+      }
+      if (!r.hasUpperBound()) {
+        signedEndKey = RowKey.toRowKey(id, new IntHandle(max.longValue())).nextPrefix();
+        // unsinged_max=0xffffffffffffffffL
```
[the remark this answers is not in the document]
Comment (qidi1) [reply tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java]: ok

File: core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala [hunk 23]
```diff
@@ -120,6 +127,133 @@ class LogicalPlanTestSuite extends BasePlanTest {
...
+    if (StoreVersion.minTiKVVersion("4", this.ti.tiSession.getPDClient)) {
+      tidbStmt.execute("""
+                         |CREATE TABLE `t1` (
+                         |  `a` BIGINT UNSIGNED  NOT NULL,
+                         |  `b` varchar(255) NOT NULL,
+                         |  `c` varchar(255) DEFAULT NULL,
+                         |  PRIMARY KEY (`a`) CLUSTERED
+                         |  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin""".stripMargin)
+    } else {
+      val config =
```
[the remark this answers is not in the document]
Comment (qidi1) [reply core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala]: ok

File: core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala [hunk 24]
```diff
@@ -516,7 +650,7 @@ class LogicalPlanTestSuite extends BasePlanTest {
     }
 
   def stringKeyRangeInDAG(dag: TiDAGRequest): String = {
-    val sb = new StringBuilder()
+    val sb = new mutable.StringBuilder()
```
[the remark this answers is not in the document]
Comment (qidi1) [reply core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala]: idea reminded me to do so

File: tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java [hunk 25]
```diff
@@ -305,47 +307,118 @@ TiKVScanPlan buildIndexScan(
...
       }
     } else {
       throw new TiClientInternalException("Empty access conditions");
     }
-    return new Pair<>(startKey, endKey);
+    return new ScanRange(signedStartKey, signedEndKey);
+  }
+
+  private ScanRange buildTableScanUnsignedKeyRangePerId(long id, IndexRange ir) {
+    BigDecimal max = new BigDecimal(Long.MAX_VALUE);
```
[the remark this answers is not in the document]
Comment (qidi1) [reply tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java:356]: OK

**Review by shiyuhang0 — APPROVED** [review]

**Review by shiyuhang0 — APPROVED** [review]

**Review by xuanyu66 — CHANGES_REQUESTED** [review]

File: core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala [hunk 26]
```diff
@@ -120,14 +125,136 @@ class LogicalPlanTestSuite extends BasePlanTest {
...
+
+    def checkResultAndExpression(
+        sql: String,
+        valueExpectation: List[String],
+        expressionExpectation: Expression): Unit = {
+      val df = spark.sql(sql)
+      val dag = extractDAGRequests(df).head
+      val rangeFilter = dag.getRangeFilter
+      val value = df.collect()
+      for (x <- value.indices) {
```
Comment (xuanyu66) [inline core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala:162]: use scalatest matcher
`value should contain theSameElementsAs valueExpectation`

Comment (qidi1) [reply core/src/test/scala/org/apache/spark/sql/catalyst/plans/logical/LogicalPlanTestSuite.scala:163]: ok

File: tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java [hunk 27]
```diff
@@ -305,62 +317,176 @@ TiKVScanPlan buildIndexScan(
...
+      if (value.compareTo(MAX_SIGNED_LONG) > 0) {
+        unsignedStartClosedKey = RowKey.toRowKey(id, new IntHandle(value.longValue()));
+        unsignedEndOpenKey = unsignedStartClosedKey.nextPrefix();
+        return new ScanRange(null, null, unsignedStartClosedKey, unsignedEndOpenKey);
+      } else {
+        signedStartClosedKey = RowKey.toRowKey(id, new IntHandle(value.longValue()));
+        signedEndOpenKey = signedStartClosedKey.nextPrefix();
+        return new ScanRange(signedStartClosedKey, signedEndOpenKey, null, null);
+      }
+    } else if (ir.hasRange()) {
```
Comment (shiyuhang0) [inline tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java:384]: we can just use `if` rather than else if because we have returned

File: tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java [hunk 28]
```diff
@@ -305,62 +317,176 @@ TiKVScanPlan buildIndexScan(
...
+                : (endKey.equals(MAX_UNSIGNED_LONG)
+                    ? BEYOND_UNSIGNED_LONG
+                    : endKey.add(BigDecimal.ONE));
+      } else {
+        endOpenKey = BEYOND_UNSIGNED_LONG;
+      }
+      boolean endOpenKeyBeyondUint64 = Objects.equals(endOpenKey, BEYOND_UNSIGNED_LONG);
+
+      // [startKey, endOpenKey) is in range of [0, MAX_INT64], the same as [0, MAX_INT64 + 1)
+      if (!endOpenKeyBeyondUint64
```
Comment (shiyuhang0) [inline tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java:420]: what if `[startKey, endOpenKey) is in range of [0, MAX_INT64]` and endOpenKeyBeyondUint64 is true

Comment (xuanyu66) [reply tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java:420]: There is already a else branch for throwing exception

File: tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java (hunk 27 above)
Comment (qidi1) [reply tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java]: changed

File: tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java (hunk 28 above)
Comment (qidi1) [reply tikv-client/src/main/java/com/pingcap/tikv/predicates/TiKVScanAnalyzer.java]: ok

**Review by xuanyu66 — APPROVED** [review]

**Review by shiyuhang0 — APPROVED** [review]
