### PR TITLE
Register udf for every sparksession

### LINKED ISSUE #1248: [BUG] ThriftServer:  Undefined function: 'ti_version'
**Describe the bug**

ThriftServer: Undefined function: 'ti_version'

**What did you do**
first beeline client: success
```
./sbin/start-thriftserver.sh
./bin/beeline
beeline> !connect jdbc:hive2://localhost:10000
0: jdbc:hive2://localhost:10000> select ti_version();
success
```

second beeline client: failed
```
./bin/beeline
beeline> !connect jdbc:hive2://localhost:10000
1: jdbc:hive2://localhost:10000> select ti_version();
Error: org.apache.spark.sql.AnalysisException: Undefined function: 'ti_version'. This function is neither a registered temporary function nor a permanent function registered in the database 'default'.; line 1 pos 7 (state=,code=0)
```
jmap shows that there are two `SparkSession` in the same JVM
```
3139:             2            288  org.apache.spark.sql.SparkSession
```

but tispark only register it's udf to the first `SparkSession`

### PR DESCRIPTION
**Pull request by birdstorm**
### What problem does this PR solve? 
Close #1248 

### What is changed and how it works?
Register udf for every sparksession

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

Follow steps in #1248.

Code changes

 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity

Related changes

 - Need to cherry-pick to the release branch
 - Need to be included in the release note

### CODE REVIEW

File: core/src/main/scala/org/apache/spark/sql/TiExtensions.scala [hunk 1]
```diff
@@ -2,14 +2,20 @@ package org.apache.spark.sql
...
-  private var tiContext: TiContext = _
+import scala.collection.mutable
 
-  def getOrCreateTiContext(sparkSession: SparkSession): TiContext = {
-    if (tiContext == null) {
-      tiContext = new TiContext(sparkSession)
+class TiExtensions extends (SparkSessionExtensions => Unit) {
+  private val tiContextMap = mutable.HashMap.empty[SparkSession, TiContext]
+
+  def getOrCreateTiContext(sparkSession: SparkSession): TiContext = synchronized {
```
Comment (marsishandsome) [inline core/src/main/scala/org/apache/spark/sql/TiExtensions.scala]: the name `TiContext` confused me, maybe should change to `TiSession`
