### PR TITLE
fix issue 1047

### LINKED ISSUE #1047: [BUG] DataTypePKSuite failed because of assertion failed
**Describe the bug**
https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tispark_regression_test_daily/runs/47/nodes/1418/steps/1732/log/?start=0

```
INFO SharedSQLContext: generate data is enabled and seed is 1566243556784
```

```
org.apache.spark.sql.types.pk.DataTypePKSuite *** ABORTED ***
[2019-08-19T19:43:10.452Z]   java.lang.RuntimeException: Unable to load a Suite class that was discovered in the runpath: org.apache.spark.sql.types.pk.DataTypePKSuite
[2019-08-19T19:43:10.452Z]   at org.scalatest.tools.DiscoverySuite$.getSuiteInstance(DiscoverySuite.scala:81)
[2019-08-19T19:43:10.452Z]   at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:38)
[2019-08-19T19:43:10.452Z]   at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:37)
[2019-08-19T19:43:10.452Z]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[2019-08-19T19:43:10.452Z]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[2019-08-19T19:43:10.452Z]   at scala.collection.Iterator$class.foreach(Iterator.scala:891)
[2019-08-19T19:43:10.452Z]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
[2019-08-19T19:43:10.452Z]   at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[2019-08-19T19:43:10.452Z]   at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[2019-08-19T19:43:10.452Z]   at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[2019-08-19T19:43:10.452Z]   ...
[2019-08-19T19:43:10.452Z]   Cause: java.lang.AssertionError: assertion failed: Generated random values(50) is less than needed(51).
[2019-08-19T19:43:10.452Z]   at scala.Predef$.assert(Predef.scala:170)
[2019-08-19T19:43:10.452Z]   at org.apache.spark.sql.test.generator.ColumnValueGenerator.next(ColumnValueGenerator.scala:281)
[2019-08-19T19:43:10.452Z]   at org.apache.spark.sql.test.generator.ColumnValueGenerator.next(ColumnValueGenerator.scala:269)
[2019-08-19T19:43:10.452Z]   at org.apache.spark.sql.test.generator.TestDataGenerator$.org$apache$spark$sql$test$generator$TestDataGenerator$$generateRandomColValue(TestDataGenerator.scala:277)
[2019-08-19T19:43:10.452Z]   at org.apache.spark.sql.test.generator.TestDataGenerator$$anonfun$org$apache$spark$sql$test$generator$TestDataGenerator$$generateRandomRow$1.apply$mcVI$sp(TestDataGenerator.scala:322)
[2019-08-19T19:43:10.452Z]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
[2019-08-19T19:43:10.452Z]   at org.apache.spark.sql.test.generator.TestDataGenerator$.org$apache$spark$sql$test$generator$TestDataGenerator$$generateRandomRow(TestDataGenerator.scala:319)
[2019-08-19T19:43:10.452Z]   at org.apache.spark.sql.test.generator.TestDataGenerator$$anonfun$generateRandomRows$2.apply(TestDataGenerator.scala:355)
[2019-08-19T19:43:10.452Z]   at org.apache.spark.sql.test.generator.TestDataGenerator$$anonfun$generateRandomRows$2.apply(TestDataGenerator.scala:354)
[2019-08-19T19:43:10.452Z]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
```

### PR DESCRIPTION
**Pull request by zhexuany**
### What problem does this PR solve? 
This PR closes #1047 

### What is changed and how it works?
The difference between `+=` and `++=`

### CODE REVIEW

File: core/src/test/scala/org/apache/spark/sql/test/generator/ColumnValueGenerator.scala [hunk 1]
```diff
@@ -236,7 +236,7 @@ case class ColumnValueGenerator(dataType: ReflectedDataType,
       generatedRandomValues = if (generateUnique) {
         assert(n <= rangeSize, "random generator cannot generate unique value less than available")
         val set: mutable.Set[Any] = mutable.HashSet.empty[Any]
-        set += specialBound.map(TestDataGenerator.hash)
+        set ++= specialBound.map(TestDataGenerator.hash)
```
Comment (birdstorm) [inline core/src/test/scala/org/apache/spark/sql/test/generator/ColumnValueGenerator.scala]: Nice catch

File: core/src/test/scala/org/apache/spark/sql/test/generator/ColumnValueGenerator.scala [hunk 2]
```diff
@@ -245,8 +245,15 @@ case class ColumnValueGenerator(dataType: ReflectedDataType,
...
+
+      val expectedGeneratedRandomValuesLen = if (generateUnique) {
+        generatedRandomValues.toSet.size
+      } else {
+        generatedRandomValues.size
+      }
+
       assert(
-        generatedRandomValues.toSet.size >= n,
+        expectedGeneratedRandomValuesLen >= n,
```
Comment (birdstorm) [inline core/src/test/scala/org/apache/spark/sql/test/generator/ColumnValueGenerator.scala]: I think it is okay to remove `toSet` and use the original way to assert.

Comment (zhexuany) [reply core/src/test/scala/org/apache/spark/sql/test/generator/ColumnValueGenerator.scala]: In this way, it can help us better locate the problem. In particular, when we are generating unique value.
