### PR TITLE
fix statistics

### LINKED ISSUE #2573: tispark 3.x version read speed is slower than tispark 2.5
**tidb version is 5.4.2
spark version 3.0 to 3.2
tispark version 3.0 to 3.1**
I used tispark2.5 before, but when i upgrade tispark version to 3.x ,I find it is slow when read tikv than tispark 2.5 version。

table info :

image

spark conf ：

image

tispark 2.5:

image

tispark 3.x:

image

### PR DESCRIPTION
**Pull request by xuanyu66**
### What problem does this PR solve? 

close #2573
In https://github.com/pingcap/tispark/pull/2259, TiResolutionRule was deleted, which cause statistics would not be collected.
Thus in https://github.com/pingcap/tispark/pull/2300/files, `ENABLE_AUTO_LOAD_STATISTICS` was considered to be useless and deprecated.

### What is changed and how it works?

- add a new ResolutionRule to collect statistics if `ENABLE_AUTO_LOAD_STATISTICS` is true.
- add documents to explain `ENABLE_AUTO_LOAD_STATISTICS`.
- fix the logicalPlan result.

### Check List 

Tests 

 - Unit test

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to be included in the release note

### CODE REVIEW

**Review by shiyuhang0 — APPROVED** [review]

File: core/src/main/scala/org/apache/spark/sql/TiContext.scala [hunk 1]
```diff
@@ -68,6 +68,8 @@ class TiContext(val sparkSession: SparkSession) extends Serializable with Loggin
   clientSession.injectCallBackFunc(CacheInvalidateListener.getInstance())
   val meta: MetaManager = new MetaManager(clientSession.getCatalog)
   val debug: DebugTool = new DebugTool
+  val autoLoad: Boolean =
+    conf.getBoolean(TiConfigConst.ENABLE_AUTO_LOAD_STATISTICS, defaultValue = true)
```
Comment (Daemonxiao) [inline core/src/main/scala/org/apache/spark/sql/TiContext.scala:72]: Shall we use `true` as the default value?

Comment (xuanyu66) [reply core/src/main/scala/org/apache/spark/sql/TiContext.scala:72]: Yes. For the former version, `true` is the default value.
And for TiDB, you can not disable statistics. https://docs.pingcap.com/tidb/dev/statistics

**Review by Daemonxiao — APPROVED** [review]

**Comment by wfxxh** [comment]
Is there any cache in tispark ? When i use this PR to run my process,the tikv read task number is correct,same as table region number.If I only process one table it is success.But if I loop process several tables it cause executor OOM。

**loop process several tables:**

image

image


**process the oom table when the loop is processed separately**

image

**my process**

image

**Comment by xuanyu66** [comment]
@wfxxh Yes, the cache is in com.pingcap.tispark.statistics.StatisticsManager
image

**Comment by wfxxh** [comment]
@xuanyu66 I does not think the cache of statisticsMap can cause the executor OOM. I print the statisticsMap size .
image
And I do not know the reasion , the executor log say nothing

**Comment by xuanyu66** [comment]
@wfxxh OK, I will merge this PR. If there is any update, you can open a new issue and we figure it out then

**Comment by wfxxh** [comment]
@xuanyu66  But the reasion when loop read tikv cause OOM is not find,It is may be a bug

**Comment by xuanyu66** [comment]
@wfxxh Can you check if OOM will happen when using the released version?

**Comment by wfxxh** [comment]
I have checked the v2.5.1 ,v3.1.1 and the master version.
The v2.5.1 version read task number is the same as this PR and equal to the table region number,but will cause OOM when loop read several table.
The v3.1.1 and the master version read task number is not correct,and equal to the table index region number.
The v2.5.1 version and the PR version is fast than v3.1.1 and master

**Comment by xuanyu66** [comment]
@wfxxh So 2.5.1 and this PR will OOM while 3.1.1 and master don't have the OOM problem, am I right?

**Comment by wfxxh** [comment]
@xuanyu66  Yes,but even it cause OOM ,there will start a new executor pod,the spark job final status is success,and it was faster than the 3.1.1 version

**Comment by xuanyu66** [comment]
@wfxxh Can we dump the memory snapshot to analyze it?

**Comment by wfxxh** [comment]
@xuanyu66 Yes I am trying to do it ,but I am run spark on k8s , I should mount a storage

**Comment by wfxxh** [comment]
@xuanyu66 I am so sorry , I can not do it ,because when the executor pod OOM it will be deleted,and the storage pvc will deleted too

**Comment by xuanyu66** [comment]
@wfxxh Can you increase your memory, and hold on for 10 minutes when the task is running. And dump the memory to analyze

**Comment by wfxxh** [comment]
@xuanyu66 How to hold on the process? sleep the thread? But the time when i sleep it may by not oom

**Comment by xuanyu66** [comment]
@wfxxh use "-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath="c:\temp\dump2.hprof" "
and use the (hostpaht)[https://kubernetes.io/docs/concepts/storage/volumes/#hostpath]

**Comment by wfxxh** [comment]
@xuanyu66 Yes,I have try this method ,but when the executor pod OOM and deleted,it will start a new pod ,and this will clear the hostpath dir.
image

**Comment by wfxxh** [comment]
@xuanyu66 I think you can merge this PR,because even it may be cause the executor oom ,but the final status is success,and it is faster

**Comment by xuanyu66** [comment]
@wfxxh You can simply use  "-XX:HeapDumpPath="c:\temp-${randomstring}\dump2.hprof"

**Comment by wfxxh** [comment]
@xuanyu66 I do not konw what is your meaning. I say when the pod oom deleted ,and restart a new one ,the hostpath in host machine will be deleted too.

**Comment by xuanyu66** [comment]
@wfxxh it's strange, normally hostpath will not be deleted. I used to build a program to collect all oom dump in last company,  
and also use hostpath.

**Comment by xuanyu66** [comment]
@wfxxh I have merged this PR and we will discuss the OOM problem here https://github.com/pingcap/tispark/issues/2587
